version: "3.9"

services:
  api:
    build: .
    container_name: rag_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_storage:/app/chroma_storage
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ingest:
    build: .
    container_name: rag_ingest
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./chroma_storage:/app/chroma_storage
    command: python -m app.ingest
    profiles:
      - ingest
