name: Docker Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  # Image will be published to GHCR as ghcr.io/<owner>/<repo>
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Docker Hub repo name (defaults to 'astrology-rag')
  DOCKERHUB_REPO: astrology-rag

jobs:
  test:
    name: Test (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install test dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install \
            fastapi==0.115.* \
            starlette==0.38.* \
            pydantic==2.* \
            httpx==0.27.* \
            pytest==8.* \
            pytest-asyncio==0.23.* \
            chromadb==0.5.5 \
            uvicorn

      - name: Run tests
        run: |
          pytest -q

  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login to GHCR with the GitHub token (no extra secrets required)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Also login to Docker Hub if secrets are provided
      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Single-arch for reliability; change to 'linux/amd64,linux/arm64' if needed
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
